<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id'            => 1,
                'parent_id'     => 0,
                'nama'          => 'Tentang Kami',
                'uri'           => 'tentang-kami',
                'link_eksternal' => 0,
                'urutan'        => 1,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 2,
                'parent_id'     => 0,
                'nama'          => 'Pendidikan',
                'uri'           => '',
                'link_eksternal' => 0,
                'urutan'        => 2,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 3,
                'parent_id'     => 2,
                'nama'          => 'Pendidikan',
                'uri'           => 'pendidikan',
                'link_eksternal' => 0,
                'urutan'        => 1,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 4,
                'parent_id'     => 2,
                'nama'          => 'Fakultas Ushuluddin dan Dakwah',
                'uri'           => 'entitas/fakultas-ushuluddin-dan-dakwah',
                'link_eksternal' => 0,
                'urutan'        => 2,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 5,
                'parent_id'     => 2,
                'nama'          => 'Fakultas Syariah',
                'uri'           => 'entitas/fakultas-syariah',
                'link_eksternal' => 0,
                'urutan'        => 3,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 6,
                'parent_id'     => 2,
                'nama'          => 'Fakultas Ilmu Tarbiyah',
                'uri'           => 'entitas/fakultas-ilmu-tarbiyah',
                'link_eksternal' => 0,
                'urutan'        => 4,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 7,
                'parent_id'     => 2,
                'nama'          => 'Fakultas Ekonomi dan Bisnis Islam',
                'uri'           => 'entitas/fakultas-ekonomi-dan-bisnis-islam',
                'link_eksternal' => 0,
                'urutan'        => 5,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 8,
                'parent_id'     => 2,
                'nama'          => 'Fakultas Adab dan Bahasa',
                'uri'           => 'entitas/fakultas-adab-dan-bahasa',
                'link_eksternal' => 0,
                'urutan'        => 6,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 9,
                'parent_id'     => 2,
                'nama'          => 'Pascasarjana',
                'uri'           => 'entitas/pascasarjana',
                'link_eksternal' => 0,
                'urutan'        => 7,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 10,
                'parent_id'     => 2,
                'nama'          => 'Lembaga',
                'uri'           => 'entitas?grup=Lembaga',
                'link_eksternal' => 0,
                'urutan'        => 8,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 11,
                'parent_id'     => 2,
                'nama'          => 'Unit Pelaksana Teknis',
                'uri'           => 'entitas?grup=Unit+Pelaksana+Teknis',
                'link_eksternal' => 0,
                'urutan'        => 9,
                'created_at'    => '2024-10-01 05:47:38',
                'updated_at'    => '2024-10-02 00:18:45',
            ],
            [
                'id'            => 12,
                'parent_id'     => 0,
                'nama'          => 'Riset dan Publikasi',
                'uri'           => '',
                'link_eksternal' => 0,
                'urutan'        => 3,
                'created_at'    => '2024-10-01 05:57:07',
                'updated_at'    => '2024-10-02 00:18:46',
            ],
            [
                'id'            => 13,
                'parent_id'     => 12,
                'nama'          => 'Omah Jurnal',
                'uri'           => 'https://ejournal.uinsaid.ac.id',
                'link_eksternal' => 1,
                'urutan'        => 1,
                'created_at'    => '2024-10-01 05:57:07',
                'updated_at'    => '2024-10-01 05:57:07',
            ],
            [
                'id'            => 14,
                'parent_id'     => 12,
                'nama'          => 'Repositori Jurnal',
                'uri'           => 'https://eprints.iain-surakarta.ac.id',
                'link_eksternal' => 1,
                'urutan'        => 2,
                'created_at'    => '2024-10-01 05:57:07',
                'updated_at'    => '2024-10-01 05:57:07',
            ],
            [
                'id'            => 15,
                'parent_id'     => 0,
                'nama'          => 'Mahasiswa Baru',
                'uri'           => 'https://admisi.uinsaid.ac.id/id',
                'link_eksternal' => 1,
                'urutan'        => 4,
                'created_at'    => '2024-10-01 05:57:07',
                'updated_at'    => '2024-10-02 00:18:46',
            ],
            [
                'id'            => 16,
                'parent_id'     => 0,
                'nama'          => 'PPID',
                'uri'           => 'ppid',
                'link_eksternal' => 0,
                'urutan'        => 5,
                'created_at'    => '2024-10-01 05:57:07',
                'updated_at'    => '2024-10-01 05:57:07',
            ],
        ];

        // Use the query builder to insert data
        $this->db->table('menu')->insertBatch($data);
    }
}
